spring:
  devtools:
    restart:
      enabled: true
  #============================================================================================
  #数据源配置
  datasource:
    url: jdbc:mysql://114.116.39.130:3306/libra?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2b8&rewriteBatchedStatements=true
    username: root
    password: Gaoxin459716010@163
    driver-class-name: com.mysql.cj.jdbc.Driver

    #指定druid数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    #druid连接池配置
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 300000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 5000000
      # 校验SQL 如果不配validationQuery项，则下面三项配置无用
      validation-query: select 1
      validation-query-timeout: 1000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 配置监控服务器
      stat-view-servlet:
        login-username: root
        login-password: root
        reset-enable: false
        url-pattern: /druid/*
        # 添加IP白名单
        #allow:
        # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
        #deny:
      web-stat-filter:
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
  banner:
    charset: utf-8
  http:
    encoding:
      charset: UTF-8

    # JPA 相关配置
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

  data:
    rest:
      base-path: /api
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  jackson:
    time-zone: Hongkong

#============================================================================================
server:
  port: 8081
  servlet:
    context-path: /


